function [X,Y,Z] = gennetmesh(net,x,y)
% Create mesh space.
% x, y should generated by linspace or something like that.

[X,Y] = meshgrid(x,y);
x1 = reshape(X,1,[]);
x2 = reshape(Y,1,[]);
z = net([x1;x2]);
Z = reshape(z,size(X));
mesh(X,Y,Z);
axis equal;
end