function [X,Y,Z] = genmesh(fcn,x,y)
% generates the meshed surface of @fcn
% if u wanna use f() pls call like 'genmesh(@f,x,y)'
% x, y: range of x and y should generated by linspace or start:step:end syntax.

[X,Y] = meshgrid(x,y);
Z = fcn(X,Y);
mesh(X,Y,Z);
end